version: '3.8'
services:
    node:
        build: .
        image: mme83/express-rest-service:app
        restart: always
        ports: 
            - ${PORT}:${PORT}
        depends_on:
            - db
        volumes:
            - ./logs:/usr/app/logs
            - ./src:/usr/app/src
        networks: 
            - app-bridge
        environment: 
            PORT: ${PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
    
    db:
        build: ./db/
        image: mme83/express-rest-service:db
        restart: always
        ports: 
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes: 
            - ./db:var/lib/postgresql/data
        networks: 
            - app-bridge
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: ${PGDATA}

networks: 
    app-bridge:
        driver: bridge

volumes: 
    db-data: