/**
 * Column model
 * @module board/model
 * @ignore
 */

import * as uuid from 'uuid';
import IColumnProps from './board.column.types';
/**
 * Column instance type
 * @typedef {Object} Column
 * @property {String} id - column id
 * @property {String} title - column title
 * @property {Number} order - column order
 */

/** Class Column representing a column */
class Column {
  id: string;

  title: string;

  order: number;

  /**
   * Creates a column instance
   * @type {Column}
   * @param {Object} [props] - an object containing Column properties
   * @param {String} [props.id] column id (auto-generated by uuid by default)
   * @param {String} [props.title="Column Title"] column title
   * @param {Number} [props.order=0] - order of the Column on the Board
   */
  constructor({ 
    id = uuid.v4(), 
    title = 'Column Title', 
    order = 0 
  }: IColumnProps = {}) {
    this.id = id;
    this.title = title;
    this.order = order;
  }
}

export default Column;